### ISSUE TITLE
DMCA Infringement

### ISSUE THREAD

**Issue by javierpignata** [FlexCoders/omnipay-govpaynet#5]
Hello,

This repository is infringing our client's copyrights. Please remove the repository immediately.

Thanks.

Kind regards.

**Comment by WanWizard** [comment]
I'm afraid you have to provide more information if you want us to take you seriously.

**Comment by WanWizard** [comment]
We have found your email in the junk folder.

I have a distinct feeling you've only done a search, and haved even bothered to look at it in detail.

We have US based clients in law enforcement who need to be able to accept payments from their clients using GovPayNet as a legal requirment. Our library is just an few lines interfacing with the public GovPayNet API, and is fully in according with the documentation we received from Bryan Holt @ GovPayNet at the time, who also helped us in initial testing.

Not a single line of code is copyright GovPayNet or its rights holders.
